/**
 * @file    git_version.h
 * @brief   Auto-generated file containing Git version information
 * 
 * This file is automatically generated during the build process.
 * DO NOT EDIT MANUALLY.
 */

#ifndef GIT_VERSION_H
#define GIT_VERSION_H

#define GIT_COMMIT_HASH "311078505730714c96bcf261d632dfb4351b46cf"
#define GIT_BRANCH_NAME "main"

#endif /* GIT_VERSION_H */
