/**
 * @file    git_version.h
 * @brief   Auto-generated file containing Git version information
 * 
 * This file is automatically generated during the build process.
 * DO NOT EDIT MANUALLY.
 */

#ifndef GIT_VERSION_H
#define GIT_VERSION_H

#define GIT_COMMIT_HASH "b5ba931302624ece578400542b7dc0a90de41c1a"
#define GIT_BRANCH_NAME "main"

#endif /* GIT_VERSION_H */
