/**
 * @file    git_version.h
 * @brief   Auto-generated file containing Git version information
 * 
 * This file is automatically generated during the build process.
 * DO NOT EDIT MANUALLY.
 */

#ifndef GIT_VERSION_H
#define GIT_VERSION_H

#define GIT_COMMIT_HASH "01011e830c962c31b570e69199599efb13582785"
#define GIT_BRANCH_NAME "main"

#endif /* GIT_VERSION_H */
