/**
 * @file    git_version.h
 * @brief   Auto-generated file containing Git version information
 * 
 * This file is automatically generated during the build process.
 * DO NOT EDIT MANUALLY.
 */

#ifndef GIT_VERSION_H
#define GIT_VERSION_H

#define GIT_COMMIT_HASH "1f9dc8117da44b51e45978ec6b25cb02d95463be"
#define GIT_BRANCH_NAME "main"

#endif /* GIT_VERSION_H */
