/**
 * @file    git_version.h
 * @brief   Auto-generated file containing Git version information
 * 
 * This file is automatically generated during the build process.
 * DO NOT EDIT MANUALLY.
 */

#ifndef GIT_VERSION_H
#define GIT_VERSION_H

#define GIT_COMMIT_HASH "12c66b7e986923429a14122baad24e1eb8199dca"
#define GIT_BRANCH_NAME "main"

#endif /* GIT_VERSION_H */
