/**
 * @file    git_version.h
 * @brief   Auto-generated file containing Git version information
 * 
 * This file is automatically generated during the build process.
 * DO NOT EDIT MANUALLY.
 */

#ifndef GIT_VERSION_H
#define GIT_VERSION_H

#define GIT_COMMIT_HASH "f5683cd7546b007f26eb2e5dba65b8fd8915f38c"
#define GIT_BRANCH_NAME "main"

#endif /* GIT_VERSION_H */
